# Generated by Django 4.2.6 on 2023-11-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='matriculaEstudante',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
