# Generated by Django 4.2.6 on 2023-10-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiblioTech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='estudanteSacado',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
