# Generated by Django 4.2.6 on 2023-12-02 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BiblioTech', '0004_delete_estudante'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='estudante',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emprestado', models.BooleanField(blank=True)),
                ('atraso', models.BooleanField(blank=True)),
                ('data_emprestimo', models.DateField(blank=True)),
                ('data_devolucao', models.DateField(blank=True)),
                ('estudante', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('livro', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BiblioTech.livro')),
            ],
        ),
    ]
