# Generated by Django 4.2.6 on 2023-12-02 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BiblioTech', '0005_livro_estudante_historico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='estudanteSacado',
        ),
    ]
