# Generated by Django 4.2.6 on 2023-12-03 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BiblioTech', '0006_remove_livro_estudantesacado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historico',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
