# Generated by Django 4.2.6 on 2023-12-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiblioTech', '0007_alter_historico_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='qtdLivrosEstoque',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
